(in-package #:sql-orm/tests)

(defun %fresh-models ()
  "Redefine models in a clean registry for isolation."
  (clrhash sql-orm::*model-registry*)
  (defmodel company ()
    (id :integer :primary-key t :autoincrement t)
    (name :text :not-null t)
    (:table companies)
    (:has-many users user :key company-id))
  (defmodel user ()
    "App user."
    (id :integer :primary-key t :autoincrement t)
    (name :text :not-null t)
    (email :text)
    (company-id :integer)
    (:table users)
    (:belongs-to company company :key company-id)
    (:has-many posts post :key user-id)
    (:compute label (self)
      (format nil "~A<~A>" (name self) (or (email self) ""))))
  (defmodel post ()
    (id :integer :primary-key t :autoincrement t)
    (title :text :not-null t)
    (user-id :integer :not-null t)
    (:table posts)
    (:belongs-to author user :key user-id)))

(deftest crud-and-calc
  (%fresh-models)
  (with-orm-connection (c :driver :sqlite3 :database-name ":memory:")
    (ensure-schema c 'company 'user 'post)
    (let* ((co (persist (make-instance 'company :name "Acme")))
           (u (persist (make-instance 'user :name "ada" :email "ada@ex.com"
                                      :company-id (id co))))
           (p1 (persist (make-instance 'post :title "Hello" :user-id (id u))))
           (p2 (persist (make-instance 'post :title "World" :user-id (id u)))))
      (declare (ignore p1 p2))
      (ok (integerp (id u)))
      (ok (equal "ada<ada@ex.com>" (label u)))
      (let ((found (find-instance 'user (id u))))
        (ok (equal "ada" (name found)))
        (ok (equal "ada@ex.com" (email found))))
      (setf (name u) "ada lovelace")
      (persist u)
      (ok (equal "ada lovelace" (name (find-instance 'user (id u)))))
      (ok (= 2 (length (posts u))))
      (ok (equal "Acme" (name (company u))))
      (ok (equal "ada lovelace" (name (author p2))))
      (ok (= 2 (count-instances 'post :where (:= :user-id (id u)))))
      (destroy p2)
      (ok (= 1 (count-instances 'post)))
      (let ((all (select-instances 'user :order-by :name)))
        (ok (= 1 (length all)))))))

(deftest select-where-order-limit
  (%fresh-models)
  (with-orm-connection (c :driver :sqlite3 :database-name ":memory:")
    (ensure-schema c 'user)
    (persist (make-instance 'user :name "b" :email "b@x"))
    (persist (make-instance 'user :name "a" :email "a@x"))
    (persist (make-instance 'user :name "c" :email "c@x"))
    (let ((rows (select-instances 'user :order-by :name :limit 2)))
      (ok (= 2 (length rows)))
      (ok (equal "a" (name (first rows))))
      (ok (equal "b" (name (second rows)))))))
