(in-package #:sql-orm/tests)

(deftest schema-diff-add-column
  (clrhash sql-orm::*model-registry*)
  (defmodel item-v1 ()
    (id :integer :primary-key t :autoincrement t)
    (name :text :not-null t)
    (:table items))
  (let ((from (schema-snapshot '(item-v1))))
    (clrhash sql-orm::*model-registry*)
    (defmodel item-v2 ()
      (id :integer :primary-key t :autoincrement t)
      (name :text :not-null t)
      (sku :text)
      (:table items))
    (let* ((to (schema-snapshot '(item-v2)))
           (ops (diff-schema from to)))
      (ok (= 1 (length ops)))
      (let ((sql (compile-sql (first ops) :dialect (make-sqlite3-dialect))))
        (ok (search "ALTER" sql :test #'char-equal))
        (ok (search "sku" sql :test #'char-equal))))))

(deftest schema-diff-create-table
  (clrhash sql-orm::*model-registry*)
  (defmodel only-user ()
    (id :integer :primary-key t)
    (name :text)
    (:table users))
  (let ((from (schema-snapshot '(only-user))))
    (defmodel only-post ()
      (id :integer :primary-key t)
      (title :text)
      (:table posts))
    (let* ((to (schema-snapshot '(only-user only-post)))
           (ops (diff-schema from to)))
      (ok (= 1 (length ops)))
      (let ((sql (compile-sql (first ops) :dialect (make-sqlite3-dialect))))
        (ok (search "CREATE" sql :test #'char-equal))
        (ok (search "posts" sql :test #'char-equal))))))

(deftest ensure-schema-roundtrip
  (clrhash sql-orm::*model-registry*)
  (defmodel note ()
    (id :integer :primary-key t :autoincrement t)
    (body :text :not-null t)
    (:table notes))
  (with-orm-connection (c :driver :sqlite3 :database-name ":memory:")
    (ensure-schema c 'note)
    (persist (make-instance 'note :body "hi"))
    (ok (equal "hi" (body (find-instance 'note 1))))))
