(in-package #:sql-orm/tests)

(defun %alter-actions (stmt)
  (slot-value stmt 'sql-query::actions))

(defun %create-table-name (stmt)
  (slot-value stmt 'sql-query::table))

(defun %create-columns (stmt)
  (slot-value stmt 'sql-query::columns))

(deftest schema-diff-add-column
  (clrhash sql-orm::*model-registry*)
  (defmodel item-v1 ()
    (id :integer :primary-key t :autoincrement t)
    (name :text :not-null t)
    (:table items))
  (let ((from (schema-snapshot '(item-v1))))
    (clrhash sql-orm::*model-registry*)
    (defmodel item-v2 ()
      (id :integer :primary-key t :autoincrement t)
      (name :text :not-null t)
      (sku :text)
      (:table items))
    (let* ((to (schema-snapshot '(item-v2)))
           (ops (diff-schema from to))
           (op (first ops))
           (action (first (%alter-actions op)))
           (col (slot-value action 'sql-query::column)))
      (ok (= 1 (length ops)))
      (ok (typep op 'sql-query:alter-table-statement))
      (ok (string-equal "items" (slot-value op 'sql-query::table)))
      (ok (typep action 'sql-query::add-column-clause))
      (ok (string-equal "sku" (sql-query:column-def-name col)))
      (ok (eq :text (sql-query:column-def-type col))))))

(deftest schema-diff-create-table
  (clrhash sql-orm::*model-registry*)
  (defmodel only-user ()
    (id :integer :primary-key t)
    (name :text)
    (:table users))
  (let ((from (schema-snapshot '(only-user))))
    (defmodel only-post ()
      (id :integer :primary-key t)
      (title :text)
      (:table posts))
    (let* ((to (schema-snapshot '(only-user only-post)))
           (ops (diff-schema from to))
           (op (first ops))
           (cols (%create-columns op)))
      (ok (= 1 (length ops)))
      (ok (typep op 'sql-query:create-table-statement))
      (ok (string-equal "posts" (%create-table-name op)))
      (ok (find "title" cols :key #'sql-query:column-def-name :test #'string-equal)))))

(deftest ensure-schema-roundtrip
  (clrhash sql-orm::*model-registry*)
  (defmodel note ()
    (id :integer :primary-key t :autoincrement t)
    (body :text :not-null t)
    (:table notes))
  (with-orm-connection (c :driver :sqlite3 :database-name ":memory:")
    (ensure-schema c 'note)
    (persist (make-instance 'note :body "hi"))
    (ok (equal "hi" (body (find-instance 'note 1))))))
